import type { WorldContent } from '../../core/world/content'
import { ECONOMY } from './economy'
import { BEACH, GATE, LONJA, WILLOW, inPinewood, layout } from './layout'
import { RESIDENTS } from './residents'

const MAYOR = 'Alcalde Mauricio Redondo'

export const aguamansa: WorldContent = {
  id: 'aguamansa',
  name: 'Aguamansa',
  tagline: 'Un pueblo de pescadores donde el lago guarda más secretos que la gente.',
  layout,
  gatheringPlace: 'lonja',
  homeLabel: 'sus casas',
  homeKeywords: ['casa', 'hogar', 'refugi', 'encierr', 'atranquen', 'suban'],
  places: [
    { id: 'lonja', name: 'la Lonja', keywords: ['lonja', 'plaza'], spots: (q) => q.where((_, t) => t.kind === 'plaza' && !t.prop) },
    {
      id: 'willow',
      name: 'el Sauce de los Chismes',
      keywords: ['sauce', 'arbol'],
      spots: (q) => q.inRect({ x0: WILLOW.x - 1, y0: WILLOW.y - 1, x1: WILLOW.x + WILLOW.size, y1: WILLOW.y + WILLOW.size }),
      linger: true,
    },
    { id: 'benches', name: 'un banco', spots: (q) => q.where((_, t) => t.prop === 'bench'), linger: true },
    { id: 'market', name: 'el mercado de pescado', keywords: ['mercado', 'puesto', 'pescaderia'], spots: (q) => q.inRect({ x0: LONJA.x0, y0: LONJA.y0, x1: LONJA.x0 + 1, y1: LONJA.y1 }) },
    { id: 'pier', name: 'el muelle', keywords: ['muelle', 'embarcadero', 'barca'], spots: (q) => q.where((_, t) => t.kind === 'bridge'), linger: true },
    { id: 'beach', name: 'la playa', keywords: ['playa', 'orilla', 'arena'], spots: (q) => q.where((_, t) => t.kind === 'sand' && !t.prop), linger: true },
    { id: 'lighthouse', name: 'el faro', keywords: ['faro'], spots: (q) => q.aroundDoor('lighthouse', 2), indoors: true },
    { id: 'inn', name: 'la posada', keywords: ['posada', 'anguila', 'taberna'], spots: (q) => q.aroundDoor('inn', 2), indoors: true, lively: true },
    { id: 'townhall', name: 'la alcaldía', keywords: ['alcaldia', 'ayuntamiento'], spots: (q) => q.aroundDoor('townhall', 2), indoors: true },
    { id: 'shrine', name: 'el santuario', keywords: ['santuario', 'templo', 'altar'], spots: (q) => q.aroundDoor('shrine', 2), indoors: true },
    { id: 'workshop', name: 'la calderería', keywords: ['caldereria', 'taller'], spots: (q) => q.aroundDoor('workshop', 2), indoors: true },
    { id: 'hut', name: 'la choza de la bruja', keywords: ['bruja', 'choza', 'carrizal'], spots: (q) => q.aroundDoor('hut', 2), indoors: true },
    { id: 'granary', name: 'el molino', keywords: ['molino', 'granero'], spots: (q) => q.aroundDoor('granary', 2), indoors: true },
    { id: 'paddy', name: 'el arrozal', keywords: ['arrozal', 'arroz', 'cosecha'], spots: (q) => q.where((_, t) => t.kind === 'field'), linger: true },
    { id: 'pinewood', name: 'el pinar', keywords: ['pinar', 'pinos', 'bosque'], spots: (q) => q.where((p, t) => t.kind === 'grass' && !t.prop && inPinewood(p.x, p.y)) },
    {
      id: 'gate',
      name: 'el puesto de guardia',
      keywords: ['puesto de guardia', 'camino del sur', 'entrada'],
      spots: (q) => q.where((p, t) => t.kind === 'path' && Math.abs(p.x - GATE.x) <= 1 && p.y >= GATE.y - 3 && p.y <= GATE.y),
    },
    { id: 'street', name: 'el camino', spots: (q) => q.where((_, t) => t.kind === 'path') },
  ],
  residents: RESIDENTS,
  speakers: {
    authority: {
      label: 'Alcalde',
      name: `${MAYOR}, alcalde de Aguamansa`,
      hint: `Habla el ${MAYOR} desde el balcón de la alcaldía. Los legales le hacen caso; los caóticos se ríen de su bigote.`,
    },
    neighbor: { label: 'Vecino', name: 'Un vecino', hint: 'Lo cuenta alguien del pueblo. Pesa quién es, su fama y qué relación tiene con cada uno.' },
    stranger: { label: 'Forastero', name: 'Un barquero desconocido', hint: 'Alguien que llegó en una barca sin nombre. Promete mucho y no dice de dónde viene.' },
    sight: { label: 'Lo vieron', name: 'Lo vieron con sus propios ojos', hint: 'Nadie lo anunció: pasó delante de ellos.' },
  },
  authorityOrigin: { building: 'townhall' },
  strangerOrigin: { x: BEACH.x0, y: 14 },
  examples: [
    {
      id: 'smoked-fish',
      truth: true,
      tone: 'confiable',
      speaker: { kind: 'authority' },
      text: '¡Por orden del Alcalde! Esta tarde se reparte pescado ahumado gratis en la Lonja para todas las familias.',
    },
    {
      id: 'lake-beast',
      truth: true,
      tone: 'urgente',
      speaker: { kind: 'neighbor', residentId: 'fermin' },
      text: 'Anoche vi una sombra enorme bajo el agua junto al muelle. Que nadie saque las barcas hasta que la guardia lo revise.',
    },
    {
      id: 'black-pearls',
      truth: false,
      tone: 'sospechoso',
      speaker: { kind: 'stranger' },
      text: 'Pago en oro cualquier perla negra. Tráiganlas esta noche al final del muelle, solos y sin decírselo a nadie.',
    },
    {
      id: 'flood',
      truth: true,
      tone: 'emergencia',
      speaker: { kind: 'authority' },
      text: '¡Alerta! El lago viene crecido y se desbordará sobre la playa: aléjense de la orilla y suban a sus casas.',
    },
  ],
  vocabulary: {
    opportunity: ['gratis', 'pescado', 'ahumado', 'oro', 'moneda', 'tesoro', 'recompensa', 'regalo', 'fiesta', 'banquete', 'perla', 'premio', 'cofre', 'barcaza', 'mercaderes'],
    danger: ['cuidado', 'peligro', 'alerta', 'sombra', 'bestia', 'serpiente', 'monstruo', 'tormenta', 'crecid', 'desborda', 'inundacion', 'no saque', 'refugi', 'incendio', 'fuego', 'llamas', 'ladron', 'contrabandista', 'lobo', 'fantasma', 'aléjense', 'alejense'],
    cues: [
      ['solos', 'vengan solos'],
      ['sin decirselo', 'no contárselo a nadie'],
      ['no se lo cuenten', 'no contárselo a nadie'],
      ['secreto', 'guardar el secreto'],
      ['esta noche', 'de noche y a escondidas'],
      ['final del muelle', 'lejos de miradas'],
      ['perla negra', 'perlas que nadie ha visto'],
    ],
  },
  hazards: [
    { visual: 'thief', place: 'market', fate: 'Un ladrón asaltó la caja de la alcaldía.' },
    { visual: 'flood', place: 'beach', fate: 'El lago se desbordó sobre la playa.' },
    { visual: 'blaze', place: 'inn', fate: 'Ardió la posada.' },
    { visual: 'caravan', place: 'pier', fate: 'Atracó una barcaza de mercaderes.' },
    { visual: 'wolves', place: 'pinewood', fate: 'Una manada de lobos bajó del pinar.' },
    { visual: 'treasure', place: 'beach', fate: 'La corriente dejó un cofre de oro en la playa.' },
    { visual: 'meteor', place: 'paddy', fate: 'Cayó una roca del cielo en el arrozal.' },
    { visual: 'monster', place: 'pier' },
    { visual: 'ghost', place: 'lighthouse' },
    { visual: 'fire', place: 'pinewood' },
    { visual: 'feast', place: 'lonja' },
  ],
  exit: 'gate',
  economy: ECONOMY,
  realm: {
    ruler: { short: 'Alcalde', title: 'el Alcalde', name: `el ${MAYOR}`, address: 'señor alcalde', seat: 'la alcaldía' },
    guild: { name: 'los contrabandistas del otro lado del lago', debtor: 'tobias' },
    petitioners: { hunger: 'lucia', granary: 'olmo', taxes: 'tobias', mood: 'rita', rationing: 'anselmo', curfew: 'marisol', guard: 'bruno' },
    festivalPlace: 'la Lonja',
  },
  outcomes: [
    { keywords: ['sombra', 'bestia', 'serpiente', 'monstruo'], visual: 'monster', label: 'apareció una bestia del lago en', witness: '¡Algo enorme sale del agua junto a {place}!' },
    { keywords: ['crecid', 'desborda', 'inundacion'], visual: 'flood', label: 'el agua lo inundó todo en', witness: '¡El lago se desborda sobre {place}!' },
    { keywords: ['lobo', 'manada'], visual: 'wolves', label: 'una manada de lobos rondó', witness: '¡Una manada de lobos acecha en {place}!' },
    { keywords: ['fantasma', 'espectro', 'ahogado'], visual: 'ghost', label: 'se vio un fantasma en', witness: '¡Un fantasma empapado flota sobre {place}!' },
    { keywords: ['incendio', 'fuego', 'llamas'], visual: 'blaze', label: 'hubo un incendio en', witness: '¡Fuego en {place}! Las llamas se extienden.' },
    { keywords: ['ladron', 'robo', 'robaron', 'contrabandista'], visual: 'thief', label: 'hubo un robo en', witness: '¡Un ladrón encapuchado roba en {place}!' },
    { keywords: ['barcaza', 'mercaderes'], visual: 'caravan', label: 'atracó una barcaza de mercaderes en', witness: '¡Una barcaza de mercaderes atraca en {place}!' },
    { keywords: ['pescado', 'banquete', 'fiesta', 'comida'], visual: 'feast', label: 'hubo festín en', witness: '¡Alguien ha servido un festín gratis en {place}!' },
    { keywords: ['perla', 'oro', 'moneda', 'tesoro', 'recompensa', 'cofre'], visual: 'treasure', label: 'el tesoro era real en', witness: '¡Hay un cofre lleno de oro en {place}!' },
  ],
  promptSetting:
    'Aguamansa es un pueblo de pescadores de fantasía a orillas de un gran lago, gobernado por el Alcalde Mauricio Redondo desde la alcaldía. Viven de la pesca y del arrozal; conviven humanos, un farero enano, un arrocero elfo, un calderero gnomo, un capitán semiorco y una bruja tiflin que vive en el carrizal. Del otro lado del lago llegan contrabandistas, y los viejos juran que algo enorme duerme bajo el agua. Todos se conocen, las noticias corren desde la Lonja y la posada La Anguila Tuerta, y el faro lo ve todo.',
  copy: {
    composerTitle: 'Nuevo pregón',
    composerSubtitle: 'Lo que pregones se oirá desde la Lonja hasta el faro.',
    broadcast: 'Pregonar',
    onAir: 'Pregonando',
    noun: 'pregón',
    emptyHint: 'Haz un pregón para ver cómo decide cada vecino.',
  },
}
