import type { PersonalityScales, ResidentProfile } from '../../core/world/content'

const SKIN = { light: 0xf3d2b6, fair: 0xe9bf9a, tan: 0xd39c72, brown: 0xa8714e, deep: 0x7a4f35, elf: 0xf6e1cf, orc: 0x93a86f, tiefling: 0x8f6fb0, gnome: 0xf0c7a4 }
const HAIR = { black: 0x2c2522, brown: 0x6b4430, chestnut: 0x8e5a36, blond: 0xe0c07a, grey: 0xb9b4ad, white: 0xece8e2, red: 0xb5532d, silver: 0xd6dde6, green: 0x6e8f5a, teal: 0x4f8a8b }

const scales = (credulity: number, bravery: number, sociability: number, authority: number, greed: number): PersonalityScales => ({ credulity, bravery, sociability, authority, greed })

/** Aguamansa's thirteen: fishers, a smuggler's debtor, a lighthouse keeper who sees everything and a newcomer who knows no one. */
export const RESIDENTS: ResidentProfile[] = [
  {
    id: 'nerea',
    name: 'Nerea Redes',
    age: 34,
    occupation: 'Pescadora',
    bio: 'Sale al lago antes del alba y vuelve con la barca llena. Cría sola a su hija Inés.',
    traits: ['valiente', 'honesta', 'madrugadora'],
    alignment: 'neutral bueno',
    personality: {
      voice: 'Llana y breve; habla del tiempo y del agua como si fueran personas.',
      values: ['su hija Inés', 'volver siempre a puerto'],
      fears: ['una tormenta con Inés en la barca', 'que el lago se vacíe de peces'],
      secret: 'Una vez vio algo enorme bajo la barca y nunca se lo contó a nadie.',
      scales: scales(0.4, 0.85, 0.5, 0.5, 0.3),
    },
    relationships: [
      { id: 'ines', label: 'hija' },
      { id: 'tobias', label: 'le vende el pescado y regatea cada moneda' },
      { id: 'fermin', label: 'le guía de vuelta con el faro' },
    ],
    home: 'nerea',
    routine: { pier: 5, beach: 2, fishMarket: 2, home: 1 },
    look: { skin: SKIN.tan, hair: HAIR.brown, hairStyle: 'bun', shirt: 0x3f6e8c, pants: 0x4a3f36, accessory: 'straw-hat', ancestry: 'human' },
  },
  {
    id: 'ines',
    name: 'Inés Redes',
    age: 9,
    occupation: 'Hija de pescadora',
    bio: 'Colecciona conchas y cuentos de monstruos del lago. Quiere ser capitana de barco.',
    traits: ['crédula', 'soñadora', 'inquieta'],
    alignment: 'caótico bueno',
    personality: {
      voice: 'Atropellada y entusiasta; pregunta todo y lo cree casi todo.',
      values: ['las aventuras', 'su madre'],
      fears: ['quedarse sola', 'la oscuridad del agua'],
      secret: 'Esconde una perla que encontró en la playa y cree que es mágica.',
      scales: scales(0.9, 0.7, 0.8, 0.4, 0.3),
    },
    relationships: [
      { id: 'nerea', label: 'madre' },
      { id: 'fermin', label: 'le cuenta historias del lago' },
      { id: 'rita', label: 'le enseña canciones de marineros' },
    ],
    home: 'nerea',
    routine: { beach: 4, fishMarket: 2, lighthouse: 1, willow: 2, home: 1 },
    look: { skin: SKIN.tan, hair: HAIR.brown, hairStyle: 'curly', shirt: 0xe8883a, pants: 0x5a4a3a, accessory: 'wooden-sword', ancestry: 'human' },
  },
  {
    id: 'tobias',
    name: 'Tobías Escamas',
    age: 51,
    occupation: 'Mercader de pescado',
    bio: 'Compra barato en el muelle y vende caro en la capital. Debe dinero a los contrabandistas del otro lado del lago.',
    traits: ['codicioso', 'nervioso', 'mentiroso'],
    alignment: 'neutral malvado',
    personality: {
      voice: 'Zalamero y rápido; todo lo convierte en trato y promete más de lo que tiene.',
      values: ['el dinero', 'su pescadería'],
      fears: ['que los contrabandistas vengan a cobrar', 'que el pueblo sepa sus cuentas'],
      secret: 'Vende el pescado de ayer como si fuera de hoy.',
      scales: scales(0.45, 0.3, 0.6, 0.35, 0.95),
    },
    relationships: [
      { id: 'nerea', label: 'le compra el pescado y le paga tarde' },
      { id: 'marisol', label: 'le fía la cuenta de la posada' },
      { id: 'bruno', label: 'desconfianza: sabe de sus deudas' },
    ],
    home: 'tobias',
    routine: { market: 5, pier: 2, inn: 2, home: 1 },
    look: { skin: SKIN.fair, hair: HAIR.grey, hairStyle: 'bald', shirt: 0x7a5a44, pants: 0x3a3a44, accessory: 'bag', ancestry: 'human', beard: HAIR.grey },
  },
  {
    id: 'marisol',
    name: 'Marisol Albahaca',
    age: 45,
    occupation: 'Posadera',
    bio: 'Regenta La Anguila Tuerta. Sabe quién llegó en qué barca y con quién se fue.',
    traits: ['chismosa', 'generosa', 'sociable'],
    alignment: 'neutral bueno',
    personality: {
      voice: 'Cálida y parlanchina; llama «cielo» a todo el mundo y exagera cada noticia.',
      values: ['una posada llena', 'que nadie pase hambre'],
      fears: ['un invierno sin viajeros', 'quedarse fuera de un chisme'],
      secret: 'Lleva años enamorada de Fermín el farero.',
      scales: scales(0.65, 0.4, 0.95, 0.5, 0.45),
    },
    relationships: [
      { id: 'fermin', label: 'le guarda el mejor guiso y suspira' },
      { id: 'tobias', label: 'le fía, aunque sabe que no pagará' },
      { id: 'rita', label: 'le paga con cena por cantar' },
    ],
    home: 'inn',
    routine: { inn: 7, market: 1, fishMarket: 1, home: 1 },
    look: { skin: SKIN.brown, hair: HAIR.black, hairStyle: 'long', shirt: 0xc86f5a, pants: 0x5a4a3a, accessory: 'apron', ancestry: 'human' },
  },
  {
    id: 'fermin',
    name: 'Fermín Nudoviejo',
    age: 168,
    occupation: 'Farero enano',
    bio: 'Enciende el faro cada noche desde hace un siglo. Desde arriba ve todo lo que pasa en el lago.',
    traits: ['escéptico', 'observador', 'solitario'],
    alignment: 'legal neutral',
    personality: {
      voice: 'Parco y gruñón; desconfía de lo que no ha visto con su catalejo.',
      values: ['la luz del faro', 'las cosas bien hechas'],
      fears: ['que el faro se apague con una barca fuera', 'hacerse viejo de verdad'],
      secret: 'Sabe que Marisol le quiere y finge no darse cuenta.',
      scales: scales(0.2, 0.7, 0.25, 0.6, 0.2),
    },
    relationships: [
      { id: 'nerea', label: 'la guía de vuelta cada noche' },
      { id: 'ines', label: 'le cuenta historias del lago' },
      { id: 'dalia', label: 'desconfianza: no le gustan sus hechizos' },
    ],
    home: 'lighthouse',
    routine: { lighthouse: 7, beach: 1, inn: 1 },
    look: { skin: SKIN.fair, hair: HAIR.white, hairStyle: 'short', shirt: 0x5e7a5a, pants: 0x4a3f36, accessory: 'glasses', ancestry: 'dwarf', beard: HAIR.white },
  },
  {
    id: 'lucia',
    name: 'Hermana Lucía',
    age: 58,
    occupation: 'Curandera del santuario',
    bio: 'Cuida enfermos y reparte sopa en el Santuario de las Aguas. Cree que el lago da y quita.',
    traits: ['compasiva', 'devota', 'paciente'],
    alignment: 'legal bueno',
    personality: {
      voice: 'Suave y serena; bendice a todos y habla de «las aguas» como de una madre.',
      values: ['cuidar a los débiles', 'la fe'],
      fears: ['una epidemia', 'que el pueblo olvide a los pobres'],
      secret: 'Dudó de su fe el invierno en que el lago se llevó a su hermano.',
      scales: scales(0.55, 0.6, 0.7, 0.75, 0.1),
    },
    relationships: [
      { id: 'anselmo', label: 'lo visita cada tarde' },
      { id: 'dalia', label: 'desconfianza: dice que sus remedios son brujería' },
      { id: 'yara', label: 'la acogió al llegar' },
    ],
    home: 'shrine',
    routine: { shrine: 6, fishMarket: 1, visit: 2, home: 1 },
    look: { skin: SKIN.light, hair: HAIR.grey, hairStyle: 'bun', shirt: 0xece8e2, pants: 0x6b6b6b, accessory: 'holy-symbol', ancestry: 'human' },
  },
  {
    id: 'bruno',
    name: 'Bruno Pardo',
    age: 40,
    occupation: 'Capitán de la guardia semiorco',
    bio: 'Manda a los cuatro guardias del pueblo. Serio, fiel al Alcalde y con más cicatrices que palabras.',
    traits: ['disciplinado', 'protector', 'desconfiado'],
    alignment: 'legal neutral',
    personality: {
      voice: 'Seco y marcial; da órdenes incluso cuando pregunta.',
      values: ['el orden', 'proteger al pueblo'],
      fears: ['fallarle al Alcalde', 'los contrabandistas'],
      secret: 'Sabe que Tobías debe dinero a los contrabandistas y no lo ha denunciado.',
      scales: scales(0.3, 0.9, 0.35, 0.9, 0.2),
    },
    relationships: [
      { id: 'tobias', label: 'lo vigila de cerca por sus deudas' },
      { id: 'gaspar', label: 'le repara las armas' },
      { id: 'nerea', label: 'la respeta: es la más valiente del muelle' },
    ],
    home: 'barracks',
    routine: { gate: 4, fishMarket: 2, pier: 2, townhall: 1, home: 1 },
    look: { skin: SKIN.orc, hair: HAIR.black, hairStyle: 'short', shirt: 0x3f6e8c, pants: 0x3a3a44, accessory: 'helmet', ancestry: 'halforc' },
  },
  {
    id: 'olmo',
    name: 'Olmo Cañaveral',
    age: 204,
    occupation: 'Arrocero elfo',
    bio: 'Cultiva el arrozal y muele el grano del pueblo. Piensa en estaciones, no en días.',
    traits: ['paciente', 'prudente', 'callado'],
    alignment: 'neutral',
    personality: {
      voice: 'Pausado y poético; habla del grano y de la luna.',
      values: ['la cosecha', 'la calma'],
      fears: ['una inundación del arrozal', 'las prisas'],
      secret: 'Guarda semillas de un arroz antiguo que ya nadie cultiva.',
      scales: scales(0.35, 0.45, 0.35, 0.55, 0.3),
    },
    relationships: [
      { id: 'anselmo', label: 'viejos amigos' },
      { id: 'marisol', label: 'le vende el arroz a la posada' },
      { id: 'tobias', label: 'no le cae bien: regatea como un buitre' },
    ],
    home: 'granary',
    routine: { paddy: 6, granary: 2, market: 1, home: 1 },
    look: { skin: SKIN.elf, hair: HAIR.blond, hairStyle: 'long', shirt: 0x6fa564, pants: 0x4a3f36, accessory: 'straw-hat', ancestry: 'elf' },
  },
  {
    id: 'dalia',
    name: 'Dalia Mareas',
    age: 71,
    occupation: 'Bruja del carrizal tiflin',
    bio: 'Vive entre los juncos y lee el futuro en las ondas del agua. Nadie sabe cuántos años tiene.',
    traits: ['misteriosa', 'paranoica', 'lista'],
    alignment: 'caótico neutral',
    personality: {
      voice: 'Enigmática y susurrante; habla en presagios y nunca responde directo.',
      values: ['los secretos del lago', 'su libertad'],
      fears: ['que la echen del pueblo', 'lo que duerme bajo el agua'],
      secret: 'Sus presagios se basan en lo que oye tras la ventana de la posada.',
      scales: scales(0.25, 0.5, 0.2, 0.1, 0.5),
    },
    relationships: [
      { id: 'lucia', label: 'rival: remedios contra plegarias' },
      { id: 'yara', label: 'la vigila: cree que esconde algo' },
      { id: 'gaspar', label: 'le compra frascos de latón' },
    ],
    home: 'hut',
    routine: { hut: 6, beach: 2, pinewood: 1, home: 1 },
    look: { skin: SKIN.tiefling, hair: HAIR.teal, hairStyle: 'long', shirt: 0x5a3f6e, pants: 0x3f3552, accessory: 'wizard-hat', ancestry: 'tiefling' },
  },
  {
    id: 'gaspar',
    name: 'Gaspar Latón',
    age: 88,
    occupation: 'Calderero gnomo',
    bio: 'Arregla ollas, anzuelos y armas. Inventa artefactos que casi nunca funcionan y exagera todos sus logros.',
    traits: ['mentiroso compulsivo', 'ingenioso', 'charlatán'],
    alignment: 'caótico neutral',
    personality: {
      voice: 'Grandilocuente y rápido; cada historia suya es más increíble que la anterior.',
      values: ['sus inventos', 'que le admiren'],
      fears: ['que nadie le crea cuando dice la verdad', 'el agua profunda'],
      secret: 'Nunca ha salido del pueblo, aunque presume de haber cruzado el lago mil veces.',
      scales: scales(0.6, 0.35, 0.8, 0.3, 0.6),
    },
    relationships: [
      { id: 'bruno', label: 'le arregla las armas a la guardia' },
      { id: 'dalia', label: 'le vende frascos de latón' },
      { id: 'ines', label: 'su héroe secreto: le regala juguetes' },
    ],
    home: 'workshop',
    routine: { workshop: 6, inn: 2, fishMarket: 1, home: 1 },
    look: { skin: SKIN.gnome, hair: HAIR.red, hairStyle: 'curly', shirt: 0x9a7a4a, pants: 0x4a3f36, accessory: 'monocle', ancestry: 'gnome' },
  },
  {
    id: 'rita',
    name: 'Rita Vela',
    age: 27,
    occupation: 'Cantora',
    bio: 'Canta en la posada y en las fiestas del muelle. Sus coplas corren más que las noticias.',
    traits: ['alegre', 'coqueta', 'impulsiva'],
    alignment: 'caótico bueno',
    personality: {
      voice: 'Cantarina y burlona; mete rimas en todo lo que dice.',
      values: ['la música', 'una buena fiesta'],
      fears: ['un pueblo triste', 'perder la voz'],
      secret: 'Escribe coplas anónimas que se burlan del Alcalde.',
      scales: scales(0.6, 0.55, 0.9, 0.25, 0.4),
    },
    relationships: [
      { id: 'marisol', label: 'le paga con cena por cantar' },
      { id: 'ines', label: 'le enseña canciones' },
      { id: 'olmo', label: 'le compone canciones que él ignora' },
    ],
    home: 'rita',
    routine: { inn: 4, fishMarket: 3, willow: 1, home: 2 },
    nightRoutine: { inn: 3, home: 2 },
    look: { skin: SKIN.brown, hair: HAIR.red, hairStyle: 'long', shirt: 0xb23a48, pants: 0x3f3552, accessory: 'lute', ancestry: 'human' },
  },
  {
    id: 'anselmo',
    name: 'Abuelo Anselmo',
    age: 83,
    occupation: 'Tejedor de redes',
    bio: 'Teje las redes de todo el muelle con las manos torcidas. Recuerda cada crecida del lago.',
    traits: ['sabio', 'frágil', 'terco'],
    alignment: 'legal bueno',
    personality: {
      voice: 'Lento y nostálgico; empieza todo con «en mis tiempos».',
      values: ['la memoria del pueblo', 'el trabajo manual'],
      fears: ['otra gran crecida', 'morir sin enseñar su oficio'],
      secret: 'La gran crecida de hace cincuenta años empezó por una compuerta que él dejó abierta.',
      scales: scales(0.5, 0.25, 0.55, 0.7, 0.2),
    },
    relationships: [
      { id: 'olmo', label: 'viejos amigos' },
      { id: 'lucia', label: 'su confesora' },
      { id: 'nerea', label: 'le teje las redes' },
    ],
    home: 'anselmo',
    routine: { home: 5, willow: 2, benches: 2, shrine: 1 },
    look: { skin: SKIN.light, hair: HAIR.white, hairStyle: 'bald', shirt: 0x8a7a6a, pants: 0x5a4a3a, accessory: 'cane', ancestry: 'human', beard: HAIR.white },
  },
  {
    id: 'yara',
    name: 'Yara',
    age: 24,
    occupation: 'Recién llegada',
    bio: 'Llegó en una barca sin nombre hace tres días. Dice que busca trabajo; no dice de dónde viene.',
    traits: ['reservada', 'desconfiada', 'curiosa'],
    alignment: 'neutral',
    personality: {
      voice: 'Cortante y prudente; responde con preguntas.',
      values: ['empezar de nuevo', 'que no le hagan preguntas'],
      fears: ['que la reconozcan', 'volver al otro lado del lago'],
      secret: 'Huyó de los contrabandistas a los que Tobías debe dinero.',
      scales: scales(0.25, 0.6, 0.3, 0.3, 0.4),
    },
    relationships: [],
    home: 'yara',
    routine: { beach: 3, pier: 2, fishMarket: 1, home: 2 },
    look: { skin: SKIN.deep, hair: HAIR.black, hairStyle: 'short', shirt: 0x5e9a8e, pants: 0x3a3a44, accessory: 'bag', ancestry: 'human' },
  },
]
