import type { WorldContent } from '../../core/world/content'
import { CEMETERY, CRYPT, GATE, OAK, PLAZA, inForest, layout, riverX } from './layout'
import { RESIDENTS } from './residents'

const BARONESS = 'Baronesa Isolda'

export const chismeroble: WorldContent = {
  id: 'chismeroble',
  name: 'Chismeroble',
  tagline: 'Donde los rumores crecen más rápido que los robles.',
  layout,
  gatheringPlace: 'plaza',
  homeLabel: 'sus casas',
  homeKeywords: ['casa', 'hogar', 'refugi', 'encierr', 'atranquen'],
  places: [
    { id: 'plaza', name: 'la Plaza del Pregón', keywords: ['plaza', 'pregon'], spots: (q) => q.where((_, t) => t.kind === 'plaza' && !t.prop) },
    {
      id: 'oak',
      name: 'el Roble Chismoso',
      keywords: ['roble'],
      spots: (q) => q.inRect({ x0: OAK.x - 1, y0: OAK.y - 1, x1: OAK.x + OAK.size, y1: OAK.y + OAK.size }),
    },
    { id: 'benches', name: 'un banco', spots: (q) => q.where((_, t) => t.prop === 'bench') },
    { id: 'market', name: 'el mercado', keywords: ['mercado', 'puesto'], spots: (q) => q.inRect({ x0: PLAZA.x0, y0: PLAZA.y0, x1: PLAZA.x0 + 1, y1: PLAZA.y1 }) },
    { id: 'tavern', name: 'la taberna', keywords: ['taberna', 'jarra', 'grifo', 'posada'], spots: (q) => q.aroundDoor('tavern', 2) },
    { id: 'forge', name: 'la forja', keywords: ['forja', 'herreria', 'herrera'], spots: (q) => q.aroundDoor('forge', 2) },
    { id: 'potions', name: 'la tienda de pociones', keywords: ['pocion', 'pocima', 'alquimista'], spots: (q) => q.aroundDoor('potions', 2) },
    { id: 'temple', name: 'el templo', keywords: ['templo', 'capilla', 'altar'], spots: (q) => q.aroundDoor('temple', 2) },
    { id: 'tower', name: 'la torre del mago', keywords: ['torre', 'maga', 'mago'], spots: (q) => q.aroundDoor('tower', 2) },
    { id: 'keep', name: 'el torreón', keywords: ['torreon', 'castillo'], spots: (q) => q.aroundDoor('keep', 2) },
    { id: 'mill', name: 'el molino', keywords: ['molino', 'pan '], spots: (q) => q.aroundDoor('mill', 2) },
    { id: 'bridge', name: 'el puente de piedra', keywords: ['puente'], spots: (q) => q.where((_, t) => t.kind === 'bridge') },
    {
      id: 'riverbank',
      name: 'la orilla del río',
      keywords: ['rio', 'orilla'],
      spots: (q) => q.where((p, t) => t.kind === 'grass' && p.x === riverX(p.y) - 1 && p.y > 8 && p.y < 26),
    },
    {
      id: 'crypt',
      name: 'la Cripta de los Susurros',
      keywords: ['cripta', 'ruinas', 'catacumba'],
      spots: (q) => q.where((p) => Math.abs(p.x - (CRYPT.x + 1)) <= 3 && Math.abs(p.y - (CRYPT.y + 1)) <= 3),
    },
    {
      id: 'cemetery',
      name: 'el cementerio',
      keywords: ['cementerio', 'camposanto', 'tumba', 'sepultur'],
      spots: (q) => q.inRect({ x0: CEMETERY.x0 + 1, y0: CEMETERY.y0 + 1, x1: CEMETERY.x1 - 1, y1: CEMETERY.y1 - 1 }),
    },
    {
      id: 'gate',
      name: 'la puerta sur',
      keywords: ['puerta sur', 'empalizada', 'puesto de guardia', 'murall'],
      spots: (q) => q.where((p, t) => t.kind === 'path' && Math.abs(p.x - GATE.x) <= 2 && p.y >= GATE.y - 3 && p.y < GATE.y),
    },
    { id: 'forest', name: 'el Bosque Susurrante', keywords: ['bosque'], spots: (q) => q.where((p, t) => t.kind === 'grass' && inForest(p.x, p.y)) },
    { id: 'field', name: 'el huerto de calabazas', keywords: ['huerto', 'calabaza', 'granja', 'cosecha'], spots: (q) => q.where((_, t) => t.kind === 'field') },
    { id: 'street', name: 'el camino', spots: (q) => q.where((_, t) => t.kind === 'path') },
  ],
  residents: RESIDENTS,
  speakers: {
    authority: {
      label: 'Baronesa',
      name: `${BARONESS}, señora de Chismeroble`,
      hint: `Habla la ${BARONESS} por boca de su heraldo. Los legales obedecen; los caóticos, no tanto.`,
    },
    neighbor: { label: 'Vecino', name: 'Un vecino', hint: 'Lo pregona alguien de la aldea. Pesa quién es, su fama y qué relación tiene con cada uno.' },
    stranger: { label: 'Forastero', name: 'Un forastero encapuchado', hint: 'Alguien envuelto en una capa que nadie ha visto antes. Promete mucho y explica poco.' },
    sight: { label: 'Lo vieron', name: 'Lo vieron con sus propios ojos', hint: 'Nadie lo anunció: pasó delante de ellos.' },
  },
  authorityOrigin: { building: 'keep' },
  strangerOrigin: { x: 14, y: PLAZA.y1 },
  examples: [
    {
      id: 'banquet',
      truth: true,
      tone: 'confiable',
      speaker: { kind: 'authority' },
      text: '¡Por orden de la Baronesa! Esta tarde hay banquete gratis en la Plaza del Pregón: jabalí asado y aguamiel para todos.',
    },
    {
      id: 'troll',
      truth: true,
      tone: 'urgente',
      speaker: { kind: 'neighbor', residentId: 'kael' },
      text: 'Cuidado: vi huellas de troll junto al puente de piedra. Que nadie lo cruce hasta que la guardia lo revise.',
    },
    {
      id: 'crypt',
      truth: false,
      tone: 'sospechoso',
      speaker: { kind: 'stranger' },
      text: 'Pago cien monedas de oro a quien baje conmigo a la cripta a medianoche. Vengan solos y no se lo cuenten a nadie.',
    },
    {
      id: 'dragon',
      truth: true,
      tone: 'emergencia',
      speaker: { kind: 'authority' },
      text: '¡Alerta! Refúgiense en sus casas y apaguen los fuegos: un dragón rojo sobrevuela el Bosque Susurrante.',
    },
  ],
  vocabulary: {
    opportunity: ['gratis', 'banquete', 'oro', 'moneda', 'tesoro', 'recompensa', 'aguamiel', 'regalo', 'fiesta', 'festin', 'pocion', 'premio', 'invitad', 'cofre', 'caravana', 'mercaderes'],
    danger: ['cuidado', 'peligro', 'alerta', 'dragon', 'troll', 'orco', 'lobo', 'bandido', 'peste', 'plaga', 'maldicion', 'ataque', 'no lo cruce', 'no crucen', 'refugi', 'incendio', 'no salgan', 'esqueleto', 'fantasma', 'bestia', 'meteorito', 'llamas', 'fuego', 'desborda', 'ladron', 'acecha'],
    cues: [
      ['solos', 'vengan solos'],
      ['no se lo cuenten', 'no contárselo a nadie'],
      ['no se lo digan', 'no contárselo a nadie'],
      ['secreto', 'guardar el secreto'],
      ['medianoche', 'a medianoche'],
      ['cripta', 'bajar a una cripta'],
      ['pacto', 'hacer un pacto'],
      ['sangre', 'firmar con sangre'],
    ],
  },
  outcomes: [
    { keywords: ['dragon'], visual: 'fire', label: 'el dragón incendió', witness: '¡Un dragón rojo escupe fuego sobre {place}!' },
    { keywords: ['troll', 'orco', 'ogro', 'bestia'], visual: 'monster', label: 'apareció una bestia en', witness: '¡Una bestia enorme con un garrote ronda {place}!' },
    { keywords: ['esqueleto', 'no muerto', 'zombi', 'tumbas'], visual: 'undead', label: 'los muertos se levantaron en', witness: '¡Esqueletos salen de las tumbas en {place}!' },
    { keywords: ['lobo', 'manada'], visual: 'wolves', label: 'una manada de lobos rondó', witness: '¡Una manada de lobos acecha en {place}!' },
    { keywords: ['fantasma', 'espectro', 'aparicion'], visual: 'ghost', label: 'se vio un fantasma en', witness: '¡Un fantasma flota sobre {place}!' },
    { keywords: ['meteorito', 'roca del cielo', 'estrella fugaz'], visual: 'meteor', label: 'cayó un meteorito en', witness: '¡Una roca en llamas cae del cielo sobre {place}!' },
    { keywords: ['inundacion', 'crecida', 'desbord'], visual: 'flood', label: 'el agua lo inundó todo en', witness: '¡El río se desborda en {place}!' },
    { keywords: ['incendio', 'fuego', 'llamas', 'en llamas'], visual: 'blaze', label: 'hubo un incendio en', witness: '¡Fuego en {place}! Las llamas se extienden.' },
    { keywords: ['ladron', 'robo', 'robaron'], visual: 'thief', label: 'hubo un robo en', witness: '¡Un ladrón encapuchado roba en {place}!' },
    { keywords: ['caravana', 'mercaderes'], visual: 'caravan', label: 'llegó una caravana a', witness: '¡Una caravana de mercaderes llega a {place}!' },
    { keywords: ['banquete', 'festin', 'fiesta', 'aguamiel', 'comida'], visual: 'feast', label: 'hubo festín en', witness: '¡Alguien ha servido un festín gratis en {place}!' },
    { keywords: ['oro', 'moneda', 'tesoro', 'recompensa', 'cofre'], visual: 'treasure', label: 'el oro era real en', witness: '¡Hay un cofre lleno de oro en {place}!' },
  ],
  promptSetting:
    'Chismeroble es una aldea de fantasía al estilo de Dragones y Mazmorras, gobernada por la Baronesa Isolda desde su torreón. En ella conviven humanos, elfos, enanos, medianos, gnomos, semiorcos y tiflins. La magia es real, los dragones y los trolls existen, en el Bosque Susurrante hay una cripta antigua, al sur está el cementerio y una empalizada con un puesto de guardia vigila la entrada del camino. Todos se conocen, el Roble Chismoso de la plaza es el centro de todos los rumores, y los chismes corren más rápido que los caballos.',
  copy: {
    composerTitle: 'Nuevo pregón',
    composerSubtitle: 'Lo que pregones se oirá en toda la aldea.',
    broadcast: 'Pregonar',
    onAir: 'Pregonando',
    noun: 'pregón',
    emptyHint: 'Haz un pregón para ver cómo decide cada residente.',
  },
}
