import type { ResidentProfile } from '../../core/world/content'

const SKIN = { light: 0xf3d2b6, fair: 0xe9bf9a, tan: 0xd39c72, brown: 0xa8714e, deep: 0x7a4f35, elf: 0xf6e1cf, orc: 0x93a86f, tiefling: 0xc4685a, gnome: 0xf0c7a4 }
const HAIR = { black: 0x2c2522, brown: 0x6b4430, chestnut: 0x8e5a36, blond: 0xe0c07a, grey: 0xb9b4ad, white: 0xece8e2, red: 0xb5532d, silver: 0xd6dde6, green: 0x6e8f5a, violet: 0x6b4f8a }

export const RESIDENTS: ResidentProfile[] = [
  {
    id: 'brunhilda',
    name: 'Brunhilda Yunquefuerte',
    age: 142,
    occupation: 'Herrera enana',
    bio: 'Forja las mejores espadas del reino y no se fía de nada que no se pueda golpear con un martillo.',
    traits: ['tozuda', 'honesta', 'desconfía de la magia'],
    alignment: 'legal neutral',
    relationships: [
      { id: 'mirabel', label: 'rival: acero contra pócimas' },
      { id: 'aldric', label: 'le forja las armas a la guardia' },
      { id: 'grum', label: 'le compra carbón y leña' },
    ],
    home: 'forge',
    routine: { forge: 7, tavern: 2, market: 1, home: 1 },
    look: { skin: SKIN.fair, hair: HAIR.red, hairStyle: 'bun', shirt: 0x7a5a44, pants: 0x4a3f36, accessory: 'apron', ancestry: 'dwarf', beard: HAIR.red },
  },
  {
    id: 'finn',
    name: 'Finn Pieligero',
    age: 38,
    occupation: 'Tabernero mediano',
    bio: 'Regenta La Jarra del Grifo. Si un rumor no ha pasado por su barra, es que no existe.',
    traits: ['chismoso', 'glotón', 'sociable'],
    alignment: 'neutral bueno',
    relationships: [
      { id: 'pip', label: 'hija' },
      { id: 'rowan', label: 'le paga en aguamiel por cantar' },
      { id: 'godric', label: 'le surte de calabazas' },
    ],
    home: 'tavern',
    routine: { tavern: 7, market: 1, plaza: 1, home: 1 },
    look: { skin: SKIN.tan, hair: HAIR.chestnut, hairStyle: 'curly', shirt: 0xc86f5a, pants: 0x5a4a3a, accessory: 'apron', ancestry: 'halfling' },
  },
  {
    id: 'mirabel',
    name: 'Mirabel Lunaverde',
    age: 312,
    occupation: 'Alquimista elfa',
    bio: 'Vende pociones de dudosa garantía. Tres siglos de vida le han enseñado que todo tiene un precio.',
    traits: ['curiosa', 'excéntrica', 'calculadora'],
    alignment: 'caótico neutral',
    relationships: [
      { id: 'zafira', label: 'su antigua maestra' },
      { id: 'brunhilda', label: 'rival: pócimas contra acero' },
      { id: 'elowen', label: 'le trae hierbas del bosque' },
    ],
    home: 'potions',
    routine: { potions: 6, forest: 2, tower: 1, market: 1 },
    look: { skin: SKIN.elf, hair: HAIR.silver, hairStyle: 'long', shirt: 0x6b4f8a, pants: 0x3f3552, accessory: 'glasses', ancestry: 'elf' },
  },
  {
    id: 'aldric',
    name: 'Sir Aldric Tiesoferro',
    age: 45,
    occupation: 'Capitán de la guardia',
    bio: 'Leal a la Baronesa hasta la médula. Ha visto demasiados timadores para creer en la buena suerte.',
    traits: ['responsable', 'desconfiado', 'metódico'],
    alignment: 'legal bueno',
    relationships: [
      { id: 'kael', label: 'la vigila de cerca' },
      { id: 'clemencia', label: 'su confesora' },
      { id: 'brunhilda', label: 'le forja las armas' },
    ],
    home: 'watch',
    routine: { street: 4, bridge: 2, keep: 2, plaza: 2, home: 1 },
    look: { skin: SKIN.fair, hair: HAIR.brown, hairStyle: 'short', shirt: 0x8a9aa8, pants: 0x3b4450, accessory: 'helmet', ancestry: 'human' },
  },
  {
    id: 'zafira',
    name: 'Zafira la Gris',
    age: 88,
    occupation: 'Maga de la torre',
    bio: 'Estudia las estrellas desde su torre. Distraída con todo excepto con las mentiras, que huele a leguas.',
    traits: ['sabia', 'distraída', 'escéptica'],
    alignment: 'neutral bueno',
    relationships: [
      { id: 'mirabel', label: 'su antigua aprendiz' },
      { id: 'agnes', label: 'viejas amigas' },
      { id: 'pip', label: 'le enseña trucos de magia' },
    ],
    home: 'tower',
    routine: { tower: 5, oak: 2, benches: 2, home: 2 },
    look: { skin: SKIN.light, hair: HAIR.white, hairStyle: 'long', shirt: 0x4f6a9a, pants: 0x3a4a6a, accessory: 'wizard-hat', ancestry: 'human', beard: HAIR.white },
  },
  {
    id: 'clemencia',
    name: 'Hermana Clemencia',
    age: 52,
    occupation: 'Clériga del templo',
    bio: 'Cura heridas, bendice cosechas y cree en la bondad de todo el mundo, a veces demasiado.',
    traits: ['altruista', 'fervorosa', 'crédula'],
    alignment: 'legal bueno',
    relationships: [
      { id: 'agnes', label: 'amiga y compañera de rezos' },
      { id: 'aldric', label: 'escucha sus confesiones' },
      { id: 'grum', label: 'lo defiende de las habladurías' },
    ],
    home: 'temple',
    routine: { temple: 6, plaza: 2, visit: 2, home: 1 },
    look: { skin: SKIN.brown, hair: HAIR.black, hairStyle: 'bun', shirt: 0xf1e6d3, pants: 0xe0d2bc, accessory: 'holy-symbol', ancestry: 'human' },
  },
  {
    id: 'pip',
    name: 'Pip Pieligero',
    age: 11,
    occupation: 'Aspirante a aventurera',
    bio: 'Sueña con matar dragones. De momento, espanta gallinas con una espada de madera.',
    traits: ['aventurera', 'inquieta', 'crédula'],
    alignment: 'caótico bueno',
    relationships: [
      { id: 'finn', label: 'padre' },
      { id: 'zafira', label: 'le enseña magia' },
      { id: 'kael', label: 'su héroe secreto' },
    ],
    home: 'tavern',
    routine: { oak: 3, plaza: 3, market: 2, bridge: 1, riverbank: 1 },
    look: { skin: SKIN.tan, hair: HAIR.chestnut, hairStyle: 'short', shirt: 0xe3a857, pants: 0x5b7a99, accessory: 'wooden-sword', ancestry: 'halfling' },
  },
  {
    id: 'grum',
    name: 'Grum Manosanchas',
    age: 30,
    occupation: 'Leñador semiorco',
    bio: 'Enorme, tímido y más tierno que el pan. Media aldea le tiene miedo sin motivo.',
    traits: ['tímido', 'bondadoso', 'huraño'],
    alignment: 'neutral bueno',
    relationships: [
      { id: 'kael', label: 'compañero de caza' },
      { id: 'clemencia', label: 'la única que lo defiende' },
      { id: 'elowen', label: 'discuten por cada árbol' },
    ],
    home: 'cabin',
    routine: { forest: 6, riverbank: 1, tavern: 1, home: 2 },
    look: { skin: SKIN.orc, hair: HAIR.black, hairStyle: 'short', shirt: 0x8a5f40, pants: 0x4a3f36, accessory: 'axe', ancestry: 'halforc' },
  },
  {
    id: 'elowen',
    name: 'Elowen Hojaplata',
    age: 120,
    occupation: 'Druida elfa',
    bio: 'Vive en lo alto de un roble. Habla con los pájaros y desconfía de todo lo que venga del castillo.',
    traits: ['soñadora', 'independiente', 'protectora del bosque'],
    alignment: 'caótico bueno',
    relationships: [
      { id: 'mirabel', label: 'le vende hierbas' },
      { id: 'grum', label: 'discuten por cada árbol' },
      { id: 'rowan', label: 'le compone canciones que ella ignora' },
    ],
    home: 'treehouse',
    routine: { forest: 5, riverbank: 2, oak: 2, home: 2 },
    look: { skin: SKIN.elf, hair: HAIR.green, hairStyle: 'long', shirt: 0x7fa876, pants: 0x5a7a5a, accessory: 'leaf-crown', ancestry: 'elf' },
  },
  {
    id: 'bartolo',
    name: 'Bartolo Cuentamonedas',
    age: 64,
    occupation: 'Prestamista gnomo',
    bio: 'Presta dinero a medio pueblo y cobra intereses al otro medio. Huele el oro a tres calles.',
    traits: ['oportunista', 'tacaño', 'bien informado'],
    alignment: 'neutral maligno',
    relationships: [
      { id: 'rosalinda', label: 'le debe una fortuna' },
      { id: 'finn', label: 'le fía la cuenta de la taberna' },
      { id: 'mirabel', label: 'socio en negocios turbios' },
    ],
    home: 'gnome',
    routine: { market: 5, tavern: 2, plaza: 2, home: 1 },
    look: { skin: SKIN.gnome, hair: HAIR.white, hairStyle: 'bald', shirt: 0x7b6a9a, pants: 0x3b3531, accessory: 'monocle', ancestry: 'gnome', beard: HAIR.white },
  },
  {
    id: 'rowan',
    name: 'Rowan Cuerdasuelta',
    age: 26,
    occupation: 'Bardo semielfo',
    bio: 'Convierte cualquier chisme en balada. Si no pasó, lo canta igual; si pasó, lo canta mejor.',
    traits: ['hablador', 'impulsivo', 'conoce a todos'],
    alignment: 'caótico neutral',
    relationships: [
      { id: 'elowen', label: 'enamorado sin remedio' },
      { id: 'finn', label: 'le paga en aguamiel' },
      { id: 'rosalinda', label: 'le escribe versos por encargo' },
    ],
    home: 'bard',
    routine: { tavern: 3, plaza: 3, oak: 2, visit: 2, street: 1 },
    look: { skin: SKIN.light, hair: HAIR.blond, hairStyle: 'long', shirt: 0x5b8fb9, pants: 0x3c4f6b, accessory: 'lute', ancestry: 'elf' },
  },
  {
    id: 'agnes',
    name: 'Abuela Agnes',
    age: 84,
    occupation: 'Curandera',
    bio: 'Ha sobrevivido a tres plagas, dos guerras y un dragón. Ningún forastero la engaña.',
    traits: ['sabia', 'paciente', 'desconfiada de forasteros'],
    alignment: 'neutral bueno',
    relationships: [
      { id: 'zafira', label: 'viejas amigas' },
      { id: 'clemencia', label: 'compañera de rezos' },
      { id: 'pip', label: 'le cuenta historias de dragones' },
    ],
    home: 'agnes',
    routine: { benches: 4, oak: 2, temple: 1, home: 3 },
    look: { skin: SKIN.fair, hair: HAIR.white, hairStyle: 'bun', shirt: 0x9a7aa0, pants: 0x5a4a5a, accessory: 'cane', ancestry: 'human' },
  },
  {
    id: 'godric',
    name: 'Godric Mazorca',
    age: 50,
    occupation: 'Granjero de calabazas',
    bio: 'Sus calabazas ganan todos los concursos. Habla poco, madruga mucho y no regala ni una semilla.',
    traits: ['cauteloso', 'ahorrador', 'madrugador'],
    alignment: 'legal neutral',
    relationships: [
      { id: 'finn', label: 'le vende calabazas' },
      { id: 'ottokar', label: 'le lleva el grano al molino' },
      { id: 'bartolo', label: 'le debe la cosecha del año pasado' },
    ],
    home: 'farm',
    routine: { field: 7, mill: 1, market: 1, home: 2 },
    look: { skin: SKIN.tan, hair: HAIR.brown, hairStyle: 'short', shirt: 0x8a9a5b, pants: 0x5a4a3a, accessory: 'straw-hat', ancestry: 'human' },
  },
  {
    id: 'ottokar',
    name: 'Maese Ottokar',
    age: 58,
    occupation: 'Molinero y panadero',
    bio: 'Su pan de centeno alimenta a toda la aldea. Trabaja de sol a sol y no tiene paciencia para cuentos.',
    traits: ['trabajador', 'pragmático', 'reservado'],
    alignment: 'legal bueno',
    relationships: [
      { id: 'godric', label: 'le trae el grano' },
      { id: 'finn', label: 'le vende el pan a la taberna' },
      { id: 'agnes', label: 'le guarda la hogaza más tierna' },
    ],
    home: 'mill',
    routine: { mill: 7, market: 1, tavern: 1, home: 1 },
    look: { skin: SKIN.fair, hair: HAIR.grey, hairStyle: 'short', shirt: 0xf1e6d3, pants: 0x6e5a4e, accessory: 'apron', ancestry: 'human', beard: HAIR.grey },
  },
  {
    id: 'kael',
    name: 'Kael Sombraceniza',
    age: 29,
    occupation: 'Cazadora tiflin',
    bio: 'Rastrea bestias por el Bosque Susurrante. Por sus cuernos, muchos creen que trae mala suerte.',
    traits: ['valiente', 'reservada', 'escéptica'],
    alignment: 'caótico bueno',
    relationships: [
      { id: 'grum', label: 'compañero de caza' },
      { id: 'aldric', label: 'la vigila sin motivo' },
      { id: 'pip', label: 'la sigue a todas partes' },
    ],
    home: 'hunter',
    routine: { forest: 4, bridge: 2, riverbank: 2, tavern: 1, home: 1 },
    look: { skin: SKIN.tiefling, hair: HAIR.violet, hairStyle: 'long', shirt: 0x4f5a4a, pants: 0x3b3531, accessory: 'longbow', ancestry: 'tiefling' },
  },
  {
    id: 'rosalinda',
    name: 'Doña Rosalinda de Vallecristal',
    age: 58,
    occupation: 'Noble venida a menos',
    bio: 'Presume de un linaje ilustre y de una fortuna que ya no tiene. Vive de apariencias y de chismes.',
    traits: ['orgullosa', 'chismosa', 'desconfiada de lo nuevo'],
    alignment: 'legal neutral',
    relationships: [
      { id: 'bartolo', label: 'le debe una fortuna' },
      { id: 'rowan', label: 'le encarga versos halagadores' },
      { id: 'clemencia', label: 'rival en la caridad del templo' },
    ],
    home: 'manor',
    routine: { plaza: 3, oak: 2, temple: 2, keep: 1, home: 2 },
    look: { skin: SKIN.light, hair: HAIR.red, hairStyle: 'bun', shirt: 0xb85d7a, pants: 0x6a3a5a, accessory: 'tiara', ancestry: 'human' },
  },
]
